project:
  type: website
  output-dir: docs

website:
  title: "Itchen Bridge"
  navbar:
    left:
      - href: index.qmd
        text: About The Bridge 
format:
  html:
    theme: darkly
    css: styles.css
    toc: true



